// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyHf48EK880eu_xfJNWbMe59IZo0OT90s',
    appId: '1:583697354660:web:5f41d365deaae994033b31',
    messagingSenderId: '583697354660',
    projectId: 'flutter-e-commerce-dec9a',
    authDomain: 'flutter-e-commerce-dec9a.firebaseapp.com',
    databaseURL: 'https://flutter-e-commerce-dec9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-dec9a.firebasestorage.app',
    measurementId: 'G-DDHXS088MW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKcl5r7g92J0KppGbDGB2GBzxPMFjnVIo',
    appId: '1:583697354660:android:a04d2707cabf73ab033b31',
    messagingSenderId: '583697354660',
    projectId: 'flutter-e-commerce-dec9a',
    databaseURL: 'https://flutter-e-commerce-dec9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-dec9a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG1e1GWAJ_KUfwbNJaCjzGHovxfprUaos',
    appId: '1:583697354660:ios:676db16e0d27fc56033b31',
    messagingSenderId: '583697354660',
    projectId: 'flutter-e-commerce-dec9a',
    databaseURL: 'https://flutter-e-commerce-dec9a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-e-commerce-dec9a.firebasestorage.app',
    iosBundleId: 'com.emad.beltaje.getxskeleton.getxSkeleton',
  );
}
